export const justDance = {
  title: "Just Dance",
  slug: "just-dance",
  artist: "Lady Gaga",
  year: "2008",
  studio: "Record Plant Studios",
  location: "Los Angeles, CA",
  bpm: 119,
  start: 4,
  end: 248,
  tracks: [
    {
      name: "Kick",
      path: "https://ioxpcmpvgermtfqxwykx.supabase.co/storage/v1/object/public/songs/justDance/kickdrum.mp3",
      volume: -32,
      pan: 0,
      mute: false,
      solo: false,
      activeBusses: [false, false],
      reverbsMix: [0.5, 0.5],
      reverbsPreDelay: [0.5, 0.5],
      reverbsDecay: [0.5, 0.5],
      reverbsBypass: [false, false],
      delaysMix: [0.5, 0.5],
      delaysTime: [1, 1],
      delaysFeedback: [0.5, 0.5],
    },
    {
      name: "Snare",
      path: "https://ioxpcmpvgermtfqxwykx.supabase.co/storage/v1/object/public/songs/justDance/snare.mp3",
      volume: -32,
      pan: 0,
      mute: false,
      solo: false,
      activeBusses: [false, false],
      reverbsMix: [0.5, 0.5],
      reverbsPreDelay: [0.5, 0.5],
      reverbsDecay: [0.5, 0.5],
      reverbsBypass: [false, false],
      delaysMix: [0.5, 0.5],
      delaysTime: [1, 1],
      delaysFeedback: [0.5, 0.5],
    },
    {
      name: "Cymbals",
      path: "https://ioxpcmpvgermtfqxwykx.supabase.co/storage/v1/object/public/songs/justDance/cymbals.mp3",
      volume: -32,
      pan: 0,
      mute: false,
      solo: false,
    },
    {
      name: "Synth 1",
      path: "https://ioxpcmpvgermtfqxwykx.supabase.co/storage/v1/object/public/songs/justDance/synth1.mp3",
      volume: -32,
      pan: 0,
      mute: false,
      solo: false,
      activeBusses: [false, false],
      reverbsMix: [0.5, 0.5],
      reverbsPreDelay: [0.5, 0.5],
      reverbsDecay: [0.5, 0.5],
      reverbsBypass: [false, false],
      delaysMix: [0.5, 0.5],
      delaysTime: [1, 1],
      delaysFeedback: [0.5, 0.5],
    },
    {
      name: "Synth 2",
      path: "https://ioxpcmpvgermtfqxwykx.supabase.co/storage/v1/object/public/songs/justDance/synth2.mp3",
      volume: -32,
      pan: 0,
      mute: false,
      solo: false,
      activeBusses: [false, false],
      reverbsMix: [0.5, 0.5],
      reverbsPreDelay: [0.5, 0.5],
      reverbsDecay: [0.5, 0.5],
      reverbsBypass: [false, false],
      delaysMix: [0.5, 0.5],
      delaysTime: [1, 1],
      delaysFeedback: [0.5, 0.5],
    },
    {
      name: "Extra Synth",
      path: "https://ioxpcmpvgermtfqxwykx.supabase.co/storage/v1/object/public/songs/justDance/extrasynth.mp3",
      volume: -32,
      pan: 0,
      mute: false,
      solo: false,
      activeBusses: [false, false],
      reverbsMix: [0.5, 0.5],
      reverbsPreDelay: [0.5, 0.5],
      reverbsDecay: [0.5, 0.5],
      reverbsBypass: [false, false],
      delaysMix: [0.5, 0.5],
      delaysTime: [1, 1],
      delaysFeedback: [0.5, 0.5],
    },
    {
      name: "Vocals",
      path: "https://ioxpcmpvgermtfqxwykx.supabase.co/storage/v1/object/public/songs/justDance/vocals.mp3",
      volume: -32,
      pan: 0,
      mute: false,
      solo: false,
      activeBusses: [false, false],
      reverbsMix: [0.5, 0.5],
      reverbsPreDelay: [0.5, 0.5],
      reverbsDecay: [0.5, 0.5],
      reverbsBypass: [false, false],
      delaysMix: [0.5, 0.5],
      delaysTime: [1, 1],
      delaysFeedback: [0.5, 0.5],
    },
  ],
};
